title = "Control-Escape"
baseURL = "https://control-escape.com"
languageCode = "en-us"
theme = "ananke"
resourceDir = "resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 15
# googleAnalytics = ""
enableRobotsTXT = true
uglyURLs = true        # Generate .html pages rather than directories

[permalinks]
articles = "/:sections/:filename"

# [languages]
# [languages.en]
# title = "Ananke"
# weight = 1
# contentDir = "content/en"
# # languageDirection = 'rtl' for Right-To-Left languages
# [languages.fr]
# title = "Ananke Fr"
# weight = 2
# contentDir = "content/fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "Vince Veselosky"
favicon = ""
site_logo = ""
description = "Helping tiny teams produce big projects fast with Python and Django."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
recent_posts_number = 15
# This is a pain, but to aggregate the recent posts from all sections, you have to list them here.
mainSections = ["django", "linux", "web"]
# This is the title of the section that will be displayed on the home page. Set manually,
# otherwise the default is the first section in the list above.
recent_copy = "Recent Articles"

# [[params.ananke_socials]]
# name = "twitter"
# url = "https://twitter.com/GoHugoIO"
