name: control-escape
networks:
  caddy_net:
    name: caddy_net
    external: true
volumes:
  redis_data:
services:
  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes
    # persistent storage
    volumes:
      - redis_data:/data
    # ports:
    #   - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - CACHE_URL=redis://redis:6379/0
      - ALLOWED_HOSTS=control-escape.com,www.control-escape.com,localhost
    user: "${USER_ID}:${GROUP_ID}"
    depends_on:
      - redis
    volumes:
      - ./var/db:/app/var/db
      - ./var/www:/app/var/www
    networks:
      - default
      - caddy_net
