#!/usr/bin/env bash

# Based on the Taskfile format from https://github.com/adriancooney/Taskfile
# Please keep functions sorted alphabetically for ease of editing.

# A useful path mod
PATH=./node_modules/.bin:$PATH

#######################################################################
# Set some commonly used globals
#######################################################################
BASE_DIR=$(cd `dirname $0`; pwd)
# Currently target 3.8
BASE_PYTHON=`which python3.8 || which python3 || which python`
PROJECT_NAME=`basename "$BASE_DIR"`

# Some ANSI colors for pretty messages
NORMAL="$(tput sgr0)"
BLACK="$(tput setaf 0)"
RED="$(tput setaf 1)"
GREEN="$(tput setaf 2)"
YELLOW="$(tput setaf 3)"
BLUE="$(tput setaf 4)"
MAGENTA="$(tput setaf 5)"
CYAN="$(tput setaf 6)"
WHITE="$(tput setaf 7)"

#######################################################################
# Function declarations
#######################################################################

#######################################################################
function audit { ## Run code quality checks
    # See https://gohugo.io/troubleshooting/audit/
    HUGO_MINIFY_TDEWOLFF_HTML_KEEPCOMMENTS=true \
    HUGO_ENABLEMISSINGTRANSLATIONPLACEHOLDERS=true \
    hugo && grep -inorE "<\!-- raw HTML omitted -->|ZgotmplZ|\[i18n\]|\(<nil>\)|(&lt;nil&gt;)|hahahugo" public/
}

#######################################################################
function build { ## Build the production site
    # Note: Django also uses /var/www/ for static files and media.
    # Building separately seems safer for now.
    hugo build --minify && cp -r public/* var/www/
}

#######################################################################
function help { ## Display usage for this application
    echo "$0 <task> <args>"
    echo "Tasks:"
    # compgen -A function | cat -n
    grep -E '^function [a-zA-Z_-]+ {.*?## .*$$' $0 | \
        sed -e 's/function //' | \
        sort | \
        awk 'BEGIN {FS = "{.*?## "}; {printf "\033[93m%-30s\033[92m %s\033[0m\n", $1, $2}'
}

#######################################################################
function lighthouse { ## Audit the site for accessibility, SEO, performance, and best practices
    lighthouse http://localhost:1313 --output html --output-path ./lighthouse-report.html --chrome-flags="--headless"
    echo "Lighthouse report generated at ./lighthouse-report.html"
}

#######################################################################
# Finally, execute it.
#######################################################################

TIMEFORMAT="Task completed in %3lR"
# Replace "help" with the name of the desired default function
time ${@:-help}
